os: unstable
image: Visual Studio 2017

environment:
  nodejs_version: "8"
  matrix:
    # - NODE_ENV: "dev"
    #   win_runtime: win-x64
    #   arch: x64
    #   plat: win32
    - NODE_ENV: "prod"
      win_runtime: win-x64
      arch: x64
      plat: win32

matrix:
  fast_finish: true

# clone_depth: 50

# configuration:
#   - Release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - SET NODE_ENV=dev
  - yarn

test_script:
  - npm run lint
  - npm test

build: false
